### ISSUE TITLE
Meetin w Peter 4/5/2024 at 4PM

### ISSUE THREAD

**Issue by JacobCavon** [EEG-project-capstone/brain_waves#11]

**Comment by ronimw** [comment]
Reach out to the woman who wrote the original dataset for accessibility

**Comment by ronimw** [comment]
Implement GUI for stimulus so it can be implemented at Harborview

**Comment by JacobCavon** [comment]
edf file type for EEGs

**Comment by ronimw** [comment]
Would we run into a storage issue with multiple EEG datasets? We could downsample to peaks after stimulus to prevent file size being too large

**Comment by ronimw** [comment]
Rodikha's paper talks about filtering down EEG data to important frequencies (windows, etc.)

**Comment by ronimw** [comment]
Turning hospital computer into remote server so we don't have to move sensitive data offsite

**Comment by JacobCavon** [comment]
June 10 2024 Peter presents to grant people

**Comment by khanh-198** [comment]
trainings and access to setup accounts in a few days
